Repository bcgov/document-generation-showcase, pull requests merged in 2019-12, with the labels that each got.

#13 Implement DGRSC-CDOGS API Wrapper & UI Updates
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/App.vue
  app/frontend/src/common/configService.js
  app/frontend/src/common/keycloakService.js
  app/frontend/src/components/Authenticated.vue
  app/frontend/src/components/AuthenticationCheck.vue
  app/frontend/src/components/FileInput.vue
  app/frontend/src/components/Footer.vue
  app/frontend/src/components/Header.vue
  app/frontend/src/components/Health.vue
  app/frontend/src/components/NavigationBar.vue
  app/frontend/src/main.js
  app/frontend/src/router/index.js
  app/frontend/src/views/CDOGS.vue
  app/frontend/src/views/Home.vue
  app/frontend/src/views/NotFound.vue
  app/frontend/src/views/Secure.vue
  app/package-lock.json
  app/package.json
  app/src/cdogsService/cdogsService.js
  app/src/cdogsService/clientConnection.js
  app/src/cdogsService/controller.js
  app/src/cdogsService/routes.js
  app/src/components/relatedLinks.js
Labels: bug, enhancement

#14 Pipeline files.
  Jenkinsfile
  Jenkinsfile.cicd
  app/frontend/jest.config.js
  app/frontend/package-lock.json
  app/frontend/package.json
  openshift/app.dc.yaml
  sonar.properties
Labels: enhancement

#17 Add about content with examples
  app/frontend/public/examples/contexts_dgrsc.json
  app/frontend/public/examples/contexts_movies.json
  app/frontend/public/examples/contexts_mx_permit.json
  app/frontend/public/examples/mx_permit_{d.permitNumber}.docx
  app/frontend/public/examples/template_information_sharing_agreement.docx
  app/frontend/public/examples/template_information_sharing_agreement.odt
  app/frontend/public/examples/template_movies.xlsx
  app/frontend/public/examples/template_powerpoint.pptx
  app/frontend/src/App.vue
  app/frontend/src/common/configService.js
  app/frontend/src/components/Authenticated.vue
  app/frontend/src/components/FileInput.vue
  app/frontend/src/components/Footer.vue
  app/frontend/src/components/Header.vue
  app/frontend/src/components/Health.vue
  app/frontend/src/components/JWTDebug.vue
  app/frontend/src/main.js
  app/frontend/src/views/CDOGS.vue
  app/frontend/src/views/Home.vue
  app/frontend/src/views/NotFound.vue
  app/src/cdogsService/cdogsService.js
  app/src/cdogsService/clientConnection.js
Labels: bug, enhancement

#18 Add missing ImageChange trigger
  openshift/app.dc.yaml
Labels: bug

#19 Update top-level readme and minor UI bugfixes
  Jenkinsfile
  Jenkinsfile.cicd
  README.md
  app/frontend/public/favicon.ico
  app/frontend/public/index.html
  app/frontend/src/App.vue
  app/frontend/src/components/Footer.vue
  app/frontend/src/components/Health.vue
  app/frontend/src/components/NavigationBar.vue
  app/frontend/src/views/Home.vue
Labels: bug, documentation

#20 Add Key/Value JSON Builder support
  app/frontend/public/index.html
  app/frontend/src/App.vue
  app/frontend/src/components/FileInput.vue
  app/frontend/src/components/Health.vue
  app/frontend/src/components/JsonBuilder.vue
  app/frontend/src/views/Home.vue
Labels: enhancement

#21 Add missing emit events on other methods
  app/frontend/src/components/FileInput.vue
  app/frontend/src/components/JsonBuilder.vue
  app/frontend/src/views/Home.vue
Labels: bug

#23 Fix footer flexbox behavior and various minor QoL Improvements
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/public/examples/contexts_hello_world.json
  app/frontend/public/examples/template_hello_world.txt
  app/frontend/src/App.vue
  app/frontend/src/assets/exampleTable.json
  app/frontend/src/components/FileInput.vue
  app/frontend/src/components/Footer.vue
  app/frontend/src/components/JsonBuilder.vue
  app/frontend/src/views/Home.vue
  app/package-lock.json
  app/package.json
Labels: bug, enhancement

#25 Add CDOGS marketing and other minor UI QoL fixes
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/public/examples/contexts_mx_permit.json
  app/frontend/src/App.vue
  app/frontend/src/assets/images/17_gov3_bc_logo.svg
  app/frontend/src/assets/images/home_flow.svg
  app/frontend/src/common/configService.js
  app/frontend/src/components/Authenticated.vue
  app/frontend/src/components/Examples.vue
  app/frontend/src/components/FileInput.vue
  app/frontend/src/components/Header.vue
  app/frontend/src/components/JWTDebug.vue
  app/frontend/src/main.js
  app/frontend/src/views/CDOGS.vue
  app/frontend/src/views/Home.vue
  app/frontend/src/views/NotFound.vue
  app/package-lock.json
Labels: bug, enhancement

#26 Update DGRSC to support optional file conversion
  app/frontend/src/App.vue
  app/frontend/src/components/FileInput.vue
  app/frontend/src/components/JsonBuilder.vue
  app/src/cdogsService/cdogsService.js
  app/src/cdogsService/controller.js
Labels: bug, enhancement

#27 Add custom Network Security Policies
  openshift/app.dc.yaml
  openshift/nsp.yaml
Labels: enhancement

#28 Link to marketing
  README.md
Labels: documentation

#29 Update documentation to match actual usage.
  app/README.md
  app/frontend/README.md
  app/frontend/package-lock.json
  openshift/README.md
Labels: documentation
