Repository bcgov/document-generation-showcase, pull requests merged in 2020-10, with the labels that each got.

#49 Updates related to Carbone 2 upgrade.
  app/frontend/package.json
  app/frontend/public/examples/contexts_carbone_2.json
  app/frontend/public/examples/contexts_header_footer_watermark.json
  app/frontend/public/examples/template_carbone_2.docx
  app/frontend/public/examples/template_header_footer_watermark.docx
  app/frontend/src/assets/exampleTable.json
  app/frontend/src/components/FileInput.vue
  app/package.json
Labels: bug, enhancement

#51 Updates for Silver Cluster
  Jenkinsfile
  Jenkinsfile.cicd
  openshift/README.md
  openshift/app.dc.yaml
  openshift/commonPipeline.groovy
Labels: bug, documentation

#52 Bugfix typo in Jenkinsfile
  Jenkinsfile
  Jenkinsfile.cicd
Labels: bug

#53 Drop SonarQube References and NSP Update
  README.md
  app/config/default.json
  app/config/test.json
  openshift/README.md
  openshift/app.dc.yaml
  openshift/nsp.yaml
Labels: documentation, enhancement
